name: Main

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: rm -f ~/.m2/settings.xml
      - name: Build Hawkbit
        # do not run tests eclipse hawkbit will do it for us
        run: cd hawkbit && mvn clean install -DskipTests
      #- uses: actions/setup-java@v2
      #  with:
      #    distribution: 'adopt'
      #    java-version: '11'
      #    overwrite-settings: false
      #- run: rm -f ~/.m2/settings.xml
      - name: Build Inoa Hawkbit
        run: mvn clean install
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - name: docker push backend
        run: docker push ghcr.io/inoa-cloud/hawkbit-server:latest
